DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS PLANT;
DROP TABLE IF EXISTS FIELD;
DROP TABLE IF EXISTS AREA;
DROP TABLE IF EXISTS ENV;
DROP TABLE IF EXISTS UNIT;
DROP TABLE IF EXISTS SENSOR;

CREATE TABLE USER (
	EMAIL TEXT PRIMARY KEY,
	PASSWORD TEXT NOT NULL,
	NAME TEXT NOT NULL,
	SUBNAME TEXT NOT NULL
);

CREATE TABLE PLANT (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	FASE1_START TEXT NOT NULL,
	FASE2_START TEXT NOT NULL,
	FASE3_START TEXT NOT NULL,
	FASE4_START TEXT NOT NULL
);

CREATE TABLE FIELD (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USER TEXT CONSTRAINT FIELD_USER_FOREIGN REFERENCES USER (EMAIL) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE AREA (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	FIELD INTEGER CONSTRAINT AREA_FIELD_FOREIGN REFERENCES FIELD (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE ENV (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	AREA INTEGER CONSTRAINT ENV_AREA_FOREIGN REFERENCES AREA (ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	SENSOR INTEGER CONSTRAINT ENV_SENSOR_FOREIGN REFERENCES SENSOR (ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	UNIT INTEGER CONSTRAINT ENV_UNIT_FOREIGN REFERENCES UNIT (ID) ON DELETE CASCADE ON UPDATE NO ACTION,
	LONG INTEGER NOT NULL,
	LAT INTEGER NOT NULL,
	DAT DATE NOT NULL,
	HUMIDITY INTEGER NOT NULL,
	TEMPERATURE INTEGER NOT NULL,
	MOISTURE INTEGER NOT NULL,
	LIGHTNESS INTEGER NOT NULL
);

CREATE TABLE UNIT (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	SYMBOL TEXT NOT NULL,
	HIGHEST INTEGER,
	LOWEST INTEGER
);

CREATE TABLE SENSOR (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	DESCRIPTION TEXT,
	MODEL TEXT NOT NULL
);