{
 "title": "Terreno 1 - Area 2",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Humedad relativa",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Hum. relativa en %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  humidity\nFROM env\nWHERE\n  area = 2\nORDER BY dat"
    }
   ]
  },
  {
   "title": "Humedad del suelo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Hum. del suelo en puntos" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  moisture\nFROM env\nWHERE\n  area = 2\nORDER BY dat"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Temp. en ºC" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  dat AS \"time\",\n  temperature\nFROM env\nWHERE\n  area = 2\nORDER BY dat"
    }
   ]
  }
 ]
}